language: node_js
node_js:
  - "node"
  - "6"
cache:
  directories:
    - "node_modules"
addons:
  postgresql: '9.4'
install:
  - npm install
script:
  - npm test coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
